# Generated by Django 4.0.1 on 2022-01-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0002_remove_blingestoque_id_alter_blingestoque_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blingestoque',
            name='sku',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
