# Generated by Django 4.0.1 on 2022-02-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0004_blingestoque_codigo_blingestoque_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blingestoque',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
